### ISSUE TITLE
Firestore gem does not work with Ruby 3

### ISSUE THREAD

**Issue by joergd** [googleapis/google-cloud-ruby#8580]
#### Environment details

  - OS: linux
  - Ruby version: 3.0
  - Gem name and version: 2.4.0

#### Code example

```ruby
# Get a document reference
nyc_ref = firestore.doc "cities/NYC"

nyc_snap = nyc_ref.get
```

#### Full backtrace

```sh
ArgumentError (wrong number of arguments (given 1, expected 0))
```

**Comment by quartzmo** [comment]
@joergd Thanks for this request! Ruby 3 support is on the way, and will address the specific issue you demonstrate here. The google-cloud-ruby gems have a couple of important dependencies that must first be updated to support Ruby 3:

* grpc - [PR #25070](https://github.com/grpc/grpc/pull/25070)
* protobuf - [PR #8134](https://github.com/protocolbuffers/protobuf/pull/8134)

**Comment by joergd** [comment]
Awesome thanks quartzmo. I downgraded my Ruby version for now - so no stress :)

**Comment by quartzmo** [comment]
Update: Both of the PRs that I linked above have been merged, but we're waiting for the next scheduled google-protobuf release, which should be in the next few weeks.

**Comment by dazuma** [comment]
Fixed in the master branch. Will release updated gems shortly.

**Comment by TylerSustare** [comment]
I'm still experiencing this in the [google-cloud-firestore](https://rubygems.org/gems/google-cloud-firestore/versions/0.21.0) gem. Is this gem updated yet? Ruby 2.7 is now unsupported 😬
